<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PulsePing</AssemblyName>
    <RootNamespace>PulsePingNative</RootNamespace>
    <Product>PulsePing Network Monitor</Product>
    <Authors>Shubham Kasar</Authors>
    <Company>Shubham Kasar</Company>
    <Description>Native Windows multi-host ICMP monitoring application.</Description>
    <Version>1.0.3</Version>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/ishubhamkasar/PulsePing</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © 2026 Shubham Kasar</Copyright>
    <ApplicationIcon>pulseping.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
